-- AICA Backoffice 1차 초안 스키마 (H2 PostgreSQL 모드 / PostgreSQL 16 호환 문법)

CREATE TABLE admin_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id        VARCHAR(50)  NOT NULL,
    name            VARCHAR(50)  NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL,          -- SUPER_ADMIN / ADMIN
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    must_change_pw  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_users_login_id UNIQUE (login_id)
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    slug        VARCHAR(50)  NOT NULL,
    description VARCHAR(200),
    sort_order  INT          NOT NULL DEFAULT 0,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_categories_slug UNIQUE (slug)
);

CREATE TABLE images (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stored_name   VARCHAR(100) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    url           VARCHAR(300) NOT NULL,
    uploaded_by   BIGINT,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_images_uploader FOREIGN KEY (uploaded_by) REFERENCES admin_users (id)
);

CREATE TABLE posts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    BIGINT,
    title          VARCHAR(200) NOT NULL,
    summary        VARCHAR(500),
    thumbnail_url  VARCHAR(300),
    thumbnail_mode VARCHAR(20)  NOT NULL DEFAULT 'AUTO',   -- AUTO(본문 첫 이미지) / MANUAL(직접 지정)
    status         VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',  -- DRAFT / PUBLISHED / HIDDEN
    blocks_json    TEXT         NOT NULL,                  -- 블록 배열 JSON
    author_id      BIGINT       NOT NULL,
    view_count     BIGINT       NOT NULL DEFAULT 0,
    published_at   TIMESTAMP,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMP,
    CONSTRAINT fk_posts_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_posts_author   FOREIGN KEY (author_id)   REFERENCES admin_users (id)
);
CREATE INDEX ix_posts_list ON posts (deleted_at, status, published_at DESC);
CREATE INDEX ix_posts_category ON posts (category_id);

-- 프론트 방문 기록 (프론트 오피스가 /api/public/track/visit 호출)
CREATE TABLE visit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visited_on  DATE         NOT NULL,
    visitor_key VARCHAR(64)  NOT NULL,
    path        VARCHAR(300),
    user_agent  VARCHAR(300),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_visit_logs_day ON visit_logs (visited_on, visitor_key);

-- 게시물 조회 기록 (일별 집계용)
CREATE TABLE post_view_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT       NOT NULL,
    viewed_on   DATE         NOT NULL,
    visitor_key VARCHAR(64),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_view_logs_post FOREIGN KEY (post_id) REFERENCES posts (id)
);
CREATE INDEX ix_post_view_logs_day ON post_view_logs (viewed_on, post_id);

-- 관리자 행위 감사 기록 (최소)
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    action      VARCHAR(50)  NOT NULL,
    target_type VARCHAR(30)  NOT NULL,
    target_id   BIGINT,
    detail      VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
