-- 게시물 버전 이력: 저장(임시저장/발행)·복원 시점의 스냅샷
CREATE TABLE post_versions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id        BIGINT       NOT NULL,
    reason         VARCHAR(30)  NOT NULL,   -- MANUAL_DRAFT / PUBLISH / RESTORE / RESTORE_BACKUP
    title          VARCHAR(200) NOT NULL,
    summary        VARCHAR(500),
    category_id    BIGINT,
    thumbnail_url  VARCHAR(300),
    thumbnail_mode VARCHAR(20)  NOT NULL DEFAULT 'AUTO',
    status         VARCHAR(20)  NOT NULL,
    blocks_json    TEXT         NOT NULL,
    created_by     BIGINT,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_versions_post FOREIGN KEY (post_id) REFERENCES posts (id)
);
CREATE INDEX ix_post_versions_post ON post_versions (post_id, id DESC);
