-- 글쓰기 템플릿: 자주 쓰는 글 구성을 저장해 두고 글쓰기 화면에서 불러온다
CREATE TABLE post_templates (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    title_hint   VARCHAR(200),
    category_id  BIGINT,
    blocks_json  TEXT         NOT NULL,
    created_by   BIGINT,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_post_templates_updated ON post_templates (updated_at DESC);
