-- 이미지 관리: 기수별 보관 폴더. 업로드한 이미지를 폴더에 넣어 두고 글쓰기 보관함에서 폴더별로 꺼내 쓴다
CREATE TABLE image_folders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(60)  NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_image_folders_name UNIQUE (name)
);

ALTER TABLE images ADD COLUMN folder_id BIGINT;
ALTER TABLE images ADD CONSTRAINT fk_images_folder FOREIGN KEY (folder_id) REFERENCES image_folders (id) ON DELETE SET NULL;
CREATE INDEX ix_images_folder ON images (folder_id, id DESC);

INSERT INTO image_folders (name, sort_order) VALUES ('1~5기', 1), ('6기', 2), ('7기', 3);
