-- 회의 반영 1차: 운영진 공지(알림) · 휴지통 이동 시 미게시 · 자산 유형 확장(동영상·문서) · 표시 이름 변경

-- 1) 휴지통: 이동 전 상태를 기억하고 status 는 HIDDEN(미게시)으로 바꾼다
ALTER TABLE posts ADD COLUMN status_before_trash VARCHAR(20);

-- 2) 자산: 종류(IMAGE | VIDEO | DOC)와 표시 이름(URL·저장 파일명은 바뀌지 않는다)
ALTER TABLE images ADD COLUMN kind VARCHAR(10) DEFAULT 'IMAGE' NOT NULL;
ALTER TABLE images ADD COLUMN display_name VARCHAR(255);
UPDATE images SET display_name = original_name WHERE display_name IS NULL;
CREATE INDEX ix_images_kind ON images (kind, id DESC);

-- 3) 운영진 공지: 최고관리자만 작성, 로그인한 운영진 전체에 상단 띠로 표시. 개인별로 닫을 수 있다
CREATE TABLE notices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    body        VARCHAR(2000),
    level       VARCHAR(10)  NOT NULL DEFAULT 'INFO',     -- INFO | WARN | URGENT
    pinned      BOOLEAN      NOT NULL DEFAULT FALSE,      -- TRUE 면 개인이 닫을 수 없다
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    starts_at   TIMESTAMP,
    ends_at     TIMESTAMP,
    created_by  BIGINT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notices_creator FOREIGN KEY (created_by) REFERENCES admin_users (id)
);
CREATE TABLE notice_dismissals (
    notice_id    BIGINT    NOT NULL,
    admin_id     BIGINT    NOT NULL,
    dismissed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notice_dismissals PRIMARY KEY (notice_id, admin_id),
    CONSTRAINT fk_nd_notice FOREIGN KEY (notice_id) REFERENCES notices (id) ON DELETE CASCADE,
    CONSTRAINT fk_nd_admin  FOREIGN KEY (admin_id)  REFERENCES admin_users (id) ON DELETE CASCADE
);
